### ISSUE TITLE
Can you provide demo code?

### ISSUE THREAD

**Issue by Changesong** [kjy7567/speech_emotion_recognition_from_log_Mel_spectrogram_using_vertically_long_patch#2]
Hello, thank you for your excellent research.
I'm trying to test your research results, but I'm having some difficulties and would like to ask for your help.
First, I created a Student object referring to the code written in the readme, and then loaded the ckpt file in the weight folder using load_state_dict. At this point, when strict=True, the following error occurred, so I set it to False:

```
RuntimeError: Error(s) in loading state_dict for Student:
        Missing key(s) in state_dict: "cls_token", "to_patch_embedding.1.weight", "to_patch_embedding.1.bias", "to_patch_embedding.2.weight", "to_pat  ch_embedding.2.bias", "to_patch_embedding.3.weight", "to_patch_embedding.3.bias", "transformer.norm.weight", "transformer.norm.bias", "transformer.la  yers.0.0.norm.weight", "transformer.layers.0.0.norm.bias", "transformer.layers.0.0.to_qkv.weight", "transformer.layers.0.0.to_out.0.weight", "transfo  rmer.layers.0.0.to_out.0.bias", "transformer.layers.0.1.net.0.weight", "transformer.layers.0.1.net.0.bias", "transformer.layers.0.1.net.1.weight", "t  ransformer.layers.0.1.net.1.bias", "transformer.layers.0.1.net.4.weight", "transformer.layers.0.1.net.4.bias", "transformer.layers.1.0.norm.weight",   "transformer.layers.1.0.norm.bias", "transformer.layers.1.0.to_qkv.weight", "transformer.layers.1.0.to_out.0.weight", "transformer.layers.1.0.to_out.  0.bias", "transformer.layers.1.1.net.0.weight", "transformer.layers.1.1.net.0.bias", "transformer.layers.1.1.net.1.weight", "transformer.layers.1.1.n  et.1.bias", "transformer.layers.1.1.net.4.weight", "transformer.layers.1.1.net.4.bias", "transformer.layers.2.0.norm.weight", "transformer.layers.2.0  .norm.bias", "transformer.layers.2.0.to_qkv.weight", "transformer.layers.2.0.to_out.0.weight", "transformer.layers.2.0.to_out.0.bias", "transformer.l  ayers.2.1.net.0.weight", "transformer.layers.2.1.net.0.bias", "transformer.layers.2.1.net.1.weight", "transformer.layers.2.1.net.1.bias", "transforme  r.layers.2.1.net.4.weight", "transformer.layers.2.1.net.4.bias", "mlp_head.weight", "mlp_head.bias".
        Unexpected key(s) in state_dict: "CE", "L1", "model_state_dict".
```

After that, I created a log mel-spectrogram image ndarray of size (128, 128) and called it like student(image), but now I get the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/emotion/long_patch_ViT/demo.py", line 137, in <module>
    main()
  File "/home/ubuntu/emotion/long_patch_ViT/demo.py", line 129, in main
    x, y = student(mel_spec)
  File "/home/ubuntu/miniforge3/envs/emotion/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniforge3/envs/emotion/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/emotion/long_patch_ViT/model.py", line 299, in forward
    x = self.encoder(img)
  File "/home/ubuntu/emotion/long_patch_ViT/model.py", line 279, in encoder
    x = self.to_patch_embedding(img)
  File "/home/ubuntu/miniforge3/envs/emotion/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniforge3/envs/emotion/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniforge3/envs/emotion/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/ubuntu/miniforge3/envs/emotion/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniforge3/envs/emotion/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniforge3/envs/emotion/lib/python3.10/site-packages/einops/layers/torch.py", line 14, in forward
    recipe = self._multirecipe[input.ndim]
KeyError: 2
```

Could you please provide information about this error or upload a demo code that we can use for testing?
Thank you.

**Comment by kjy7567** [comment]
Hello, Changesong.
You can load the trained weights using "model_state_dict" key
I save the model as a python Dict() format
Like below:
```python
torch.save({
            'model_state_dict': model.state_dict(),
            'CE': cross_entropy_loss
            'L1': L1_loss
            ...
            }, PATH)
```
You can ignore keys like "CE", "L1" that are not used but not removed
Just use the "model_state_dict" key.
```python
# model.load_state_dict(torch.load(PATH_WEIGHT_FILE)['model_state_dict'])
model.load_state_dict(torch.load('./weight/teacher_92.64_CREMA_D.ckpt')['model_state_dict'])
```

**Comment by Changesong** [comment]
Thank you. I loaded the model as you said and it works fine.
